### PR TITLE
mark factories as final

### PR DESCRIPTION
**Pull request by sandrokeil**
As mentioned in #116

### CODE REVIEW

**Comment by prolic** [comment]
Thanks.

**Comment by codeliner** [comment]
sorry for being late, but the factory changes definitely require a new major version. For example I extend from the factories to override the containerId. I can now achieve the same with the new "call static" feature but I need to migrate my application, so a new major version with a migration path is needed and we also need to align the docs!

Question: Is it possible to keep BC and mark for example `Factory::containerId` as deprecated first? Then we can remove the message with the next major release.

**Comment by prolic** [comment]
I am fine with a new major release, too.
We can implement the event store adapter strategies and allow php 7 only. would be a good bunch of new features, so let's work on that. I can start with adapter strategies and php7 migration in about 4 weeks, when i am in the philippines.

**Comment by codeliner** [comment]
I won't have much time in March and April but hopefully have more time again with the beginning of Mai. But we can of course start (or better continue) with implementing the changes and if it takes a bit longer this time it is not really a problem as our current versions already have a rich feature set.

**Comment by sandrokeil** [comment]
@prolic I think we should not bring a new major release at this time, maybe at the end of the year with PHP 7 only support. We should also make the upgrade path simply like ZF2 does. I can remove the final keyword.

@codeliner A possibility is to call `containerId()` in the constructor, but how to use it together with the parameter `configId`?

In [event-store](https://github.com/prooph/event-store/pull/165) we have a drop in replacement.

**Pull request merged**
