### PR TITLE
Queue commands and pass pending commands to exception

### PR DESCRIPTION
**Pull request by codeliner**

### CODE REVIEW

**Comment by codeliner** [comment]
ping @prolic

**Comment by prolic** [comment]
php cs issues

**Comment by codeliner** [comment]
damn, always the same, sorry :)

**Comment by sstok** [comment]
You may want to enable https://styleci.io/ ;)

And there is a Gush command to update your pull-request.
https://github.com/gushphp/gush/blob/master/src/Command/Util/StyleCIPatchCommand.php

Simple configure Gush and run `gush.phar pull-request:styleci 97` (only updates the remote branch but not the locale branch (yet) so make sure to pull-in the remote changes).

**Comment by codeliner** [comment]
@sstok yeah, that is an idea or just a [phpstorm file watcher](http://www.sasaprolic.com/2015/11/php-cs-fixer-in-phpstorm-with-file.html) ;) 

I'll definitely try `gush branch:changelog`. We have so many packages at prooph and it is really a time consuming task to prepare releases. Today or tomorrow new major versions for a couple of components will be released. I'm curious if gush can help me speeding up the process.

**Comment by sstok** [comment]
Oh thanks for the tip :+1: 

If `gush branch:changelog` doesn't work as you would like it to please open an issue so can improve it :smiley:

**Comment by sstok** [comment]
FYi, I'm no longer involved in Gush but I did create something else.
https://github.com/park-manager/hubkit

You can use the `changelog` command create a fully categorized changelog, but there is a minor catch. You must use the `merge` command to merge your pull-requests so that the category (and special labels like "Deprecation removal") are stored within the merge commit.

I'm using it on a daily basis now, and the only thing missing is documentation. But if you have any questions feel free the ask 👍

**Pull request merged**
